apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-deployment
  namespace: locust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
      annotations:
        statefulset.kubernetes.io/pod-name: locust
    spec:
      containers:
      - name: locust
        image: ghcr.io/scilifelabdatacentre/serve-load-testing:main-20240429-1418
        ports:
        - containerPort: 8089
        envFrom:
        - secretRef:
            name: locust-secrets
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "64Mi"
      - name: locust-db
        image: cyberw/locust-timescale:6
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: locust-secrets
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        volumeMounts:
        - name: data-pvc
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data-pvc
        persistentVolumeClaim:
          claimName: data-pvc
