apiVersion: v1
kind: Secret
metadata:
  name: locust-secrets
type: Opaque
data:
  SERVE_USERNAME: Y2hhbmdlLW1l
  SERVE_PASS: Y2hhbmdlLW1l
  SERVE_LOCUST_TEST_USER_PASS: cGFzc3dvcmQxMjM=
  SERVE_LOCUST_DO_CREATE_OBJECTS: ZmFsc2U=
  PROTECTED_PAGE_RELATIVE_URL: Y2hhbmdlLW1l
  POSTGRES_PASSWORD: Q2JpNk42RWVSUGc2RTdC
  TIMESCALEDB_TELEMETRY: b2Zm
