apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serve-locust
spec:
  destination:
    namespace: locust
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/ScilifelabDataCentre/serve-load-testing
    path: manifests
    targetRevision: develop
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
